   # t = Binary_Search_Tree()
    # t.add(10)
    # t.add(5)
    # t.add(20)
    # t.add(2)
    # t.add(8)
    # t.add(14)
    # t.add(30)

    # t.search(5)
    # t.search(13)
    # t.search(20)
    # t.search(8)